# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            김성훈의 개발노트
tagline:          'jekyll-theme-hyde'
description:      '백엔드 개발자 김성훈의 개발노트입니다.'
url:              http://fredzenobius.github.io
baseurl:          ''

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
